#!/bin/bash

./batch_relink . ~ .inputrc .tmux.conf
./batch_relink . ~ .ssh/

./batch_relink . ~ .bashrc
./batch_relink . ~ .gitconfig .vimrc

./batch_relink . ~ .pythonrc

pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
